function [ data ] = loadLeCroy( filename, regex )
% data = LOADLECROY(filename, regex) reads all data files generated by the
% LeCroy SDA 825Zi-A oscilloscope from the "raw-data" directory that match
% the regular expression REGEX and loads them into the DATA matrix.
% Afterwards, the DATA matrix is saved as FILENAME.

assert(ischar(filename),'The given FILENAME is not a character array!');
assert(ischar(regex),'The given REGEX is not a character array!');
assert(isdir('raw-data'),'There is no directory named raw-data');

cd('raw-data');
filenames = dir(regex);

assert(not(isempty(filenames)),'REGEX has no matches!');
dataSize = size(csvread(filenames(1).name,5));

assert(dataSize(2)==1,'Files include more than one data column!');
data = zeros(dataSize(1),length(filenames));

for i=1:length(filenames)
    data(:,i) = csvread(filenames(i).name,5);
end

cd('..');
data = single(data);
save(filename,'-v7.3','data');

end
