tic
switch type
    case 'table'
%% create new mat data and 3 Ch tables
%plotCrossCorrelationDelaySeries;
%seriesQuadratures('Channels',1:3,'Offset','local','Piezo','yes');
%g2SeriesFromQuadratures(1000,'Weight','yes','UseX','X1','Parameter','delay');
    listOfParams = struct('Type',{'fullcircle'},'Position',{[4 0.5]});
    makeSelectionPlots('table','ListOfParams',listOfParams,'RecomputeTheta',true,...
            'RecomputeOrth',true,'saveOrth',true,'ChannelAssignment',[3,1,2],...
            'SavePostselection',true,'SaveTheta',true,'GetDelay',true,'RemoveModulation',false,'XUnit','ps','VaryAPS',false);

    case 'radiusSeries'
% %% Radius Series
     listOfParams = struct('Type',{'fullcircle'},'Position',{[0.5 0.25],[1,0.4],[1.5 0.4],...
            [2 0.4],[3 0.4],[5 0.4],[6 0.4],[7 0.4],[8 0.4],[9 0.4],[10 0.4],[11 0.4],[12 0.4],[13 0.4]});
       makeSelectionPlots('table','ListOfParams',listOfParams,'RecomputeTheta',false,'RecomputeOrth',false,'saveOrth',false,...
           'ChannelAssignment',[3,1,2],...
            'SavePostselection',true,'SaveTheta',false,'GetDelay',true,'RemoveModulation',false,'XUnit','ps','VaryAPS',false,'FitType','voigt');
        
         case 'thicknessSeries'
     listOfParams = struct('Type',{'fullcircle'},'Position',{[3 0.1],[3 0.2],[3 0.3],[3 0.4],[3 0.5],[3 0.6],[3 0.7],[3 0.8],[3 0.9],[3 1]});
       makeSelectionPlots('table','ListOfParams',listOfParams,'RecomputeTheta',false,'RecomputeOrth',false,'saveOrth',false,...
           'ChannelAssignment',[3,1,2],...
            'SavePostselection',true,'SaveTheta',false,'GetDelay',true,'RemoveModulation',false,'XUnit','ps','VaryAPS',false,'FitType','voigt');
    
%     listOfParams = struct('Type',{'fullcircle'},'Position',{[0.5 0.25],[1 0.25],...
%         [2 0.5],[3 0.5],[4 0.5],[5 0.5],[6 0.5],[7 0.5],[8 0.5]});
%    makeSelectionPlots('radiusPlots','ListOfParams',listOfParams,'RecomputeTheta',false,'RecomputeOrth',false,'saveOrth',false,...
%         'SavePostselection',false,'SaveTheta',false,'GetDelay',true,'RemoveModulation',true,'XUnit','ps','VaryAPS',true,'FitType','voigt');
%     
%% Radius Series rem mod
%  listOfParams = struct('Type',{'fullcircle'},'Position',{[0.5 0.25]});
%    makeSelectionPlots('table','ListOfParams',listOfParams,'RecomputeTheta',true,'RecomputeOrth',true,'saveOrth',true,...
%         'SavePostselection',true,'SaveTheta',true,'GetDelay',true,'RemoveModulation',true,'XUnit','ps','VaryAPS',true,'FitType','voigt');
%   listOfParams = struct('Type',{'fullcircle'},'Position',{[1 0.25],...
%         [2 0.5],[3 0.5],[4 0.5],[5 0.5],[6 0.5],[7 0.5],[8 0.5]});
%    makeSelectionPlots('table','ListOfParams',listOfParams,'RecomputeTheta',false,'RecomputeOrth',false,'saveOrth',false,...
%         'SavePostselection',true,'SaveTheta',false,'GetDelay',true,'RemoveModulation',true,'XUnit','ps','VaryAPS',true,'FitType','voigt');
%     listOfParams = struct('Type',{'fullcircle'},'Position',{[0.5 0.25],[1 0.25],...
%         [2 0.5],[3 0.5],[4 0.5],[5 0.5],[6 0.5],[7 0.5],[8 0.5]}); 
%      makeSelectionPlots('radiusPlots','ListOfParams',listOfParams,'RecomputeTheta',false,'RecomputeOrth',false,'saveOrth',false,...
%         'SavePostselection',false,'SaveTheta',false,'GetDelay',true,'RemoveModulation',true,'XUnit','ps','VaryAPS',true,'FitType','voigt');
    
%% Thickness Series
% listOfParamsT = struct('Type',{'fullcircle'},'Position',{[0 0.05],[0 0.1],[0,0.15],...
%         [0 0.2],[0 0.4],[0 0.6],[0 0.8],[0 1]});    
% makeSelectionPlots('radiusPlots','ListOfParams',listOfParamsT,'RecomputeTheta',false,...
%     'RecomputeOrth',false,'saveOrth',false,...
%     'SavePostselection',false,'SaveTheta',false,'GetDelay',true,'RemoveModulation',false,'XUnit','ps','VaryAPS',true);
end;
toc