tic
switch type
    case 'table'
%% create new mat data and 3 Ch tables
%plotCrossCorrelationDelaySeries;
%seriesQuadratures('Channels',1:3,'Offset','local','Piezo','yes');
%g2SeriesFromQuadratures(1000,'Weight','yes','UseX','X1','Parameter','delay');
    listOfParams = struct('Type',{'fullcircle'},'Position',{[6.5 0.4]});
    makeSelectionPlots('table','ListOfParams',listOfParams,'RecomputeTheta',true,...
            'RecomputeOrth',true,'saveOrth',true,'ChannelAssignment',[3,1,2],...
            'SavePostselection',true,'SaveTheta',true,'GetDelay',true,'RemoveModulation',false,'XUnit','ps','VaryAPS',false,'CorrRemove','yes');

    case 'radiusSeries'
% %% Radius Series
        t = 0.4;
       % t = 0.1;
     listOfParams = struct('Type',{'fullcircle'},'Position',{[0.5 t],[1,t],[1.5 t],...
            [2 t],[3 t],[4 t],[5 t],[6 t],[7 t],[8 t],[9 t],[10 t],[11 t]});
       makeSelectionPlots('table','ListOfParams',listOfParams,'RecomputeTheta',false,'RecomputeOrth',false,'saveOrth',false,...
           'ChannelAssignment',[3,1,2],...
            'SavePostselection',true,'SaveTheta',false,'GetDelay',true,'RemoveModulation',false,'XUnit','ps','VaryAPS',false,'FitType','noFit','CorrRemove','yes');
         makeSelectionPlots('table','ListOfParams',listOfParams,'RecomputeTheta',false,'RecomputeOrth',false,'saveOrth',false,...
           'ChannelAssignment',[3,1,2],'SavePostselection',false,'SaveTheta',false,...
           'GetDelay',true,'RemoveModulation',true,'Range',[13 20],'XUnit','ps','VaryAPS',false,'FitType','noFit','CorrRemove','yes');
        
         t = 0.05;
     listOfParams = struct('Type',{'fullcircle'},'Position',{[0.5 t],[1,t],[1.5 t],...
            [2 t],[3 t],[4 t],[5 t],[6 t],[7 t],[8 t],[9 t],[10 t],[11 t],[12 t],[13 t]});
       makeSelectionPlots('table','ListOfParams',listOfParams,'RecomputeTheta',false,'RecomputeOrth',false,'saveOrth',false,...
           'ChannelAssignment',[3,1,2],...
            'SavePostselection',true,'SaveTheta',false,'GetDelay',true,'RemoveModulation',false,'XUnit','ps','VaryAPS',false,'FitType','noFit','CorrRemove','yes');
        
         case 'thicknessSeries'
     a = 6.5;
listOfParams = struct('Type',{'fullcircle'},'Position',{[a 0.1],[a 0.2],[a 0.3],[a 0.4],[a 0.5],[a 0.6],[a 0.7],[a 0.8],[a 0.9],[a 1]});
            
       makeSelectionPlots('table','ListOfParams',listOfParams,'RecomputeTheta',false,'RecomputeOrth',false,'saveOrth',false,...
           'ChannelAssignment',[3,1,2],...
            'SavePostselection',true,'SaveTheta',false,'GetDelay',true,'RemoveModulation',false,'XUnit','ps','VaryAPS',false,'FitType','noFit','CorrRemove','yes');
    
%     listOfParams = struct('Type',{'fullcircle'},'Position',{[0.5 0.25],[1 0.25],...
%         [2 0.5],[3 0.5],[4 0.5],[5 0.5],[6 0.5],[7 0.5],[8 0.5]});
%    makeSelectionPlots('radiusPlots','ListOfParams',listOfParams,'RecomputeTheta',false,'RecomputeOrth',false,'saveOrth',false,...
%         'SavePostselection',false,'SaveTheta',false,'GetDelay',true,'RemoveModulation',true,'XUnit','ps','VaryAPS',true,'FitType','voigt');
%     
%% Radius Series rem mod
%  listOfParams = struct('Type',{'fullcircle'},'Position',{[0.5 0.25]});
%    makeSelectionPlots('table','ListOfParams',listOfParams,'RecomputeTheta',true,'RecomputeOrth',true,'saveOrth',true,...
%         'SavePostselection',true,'SaveTheta',true,'GetDelay',true,'RemoveModulation',true,'XUnit','ps','VaryAPS',true,'FitType','voigt');
%   listOfParams = struct('Type',{'fullcircle'},'Position',{[1 0.25],...
%         [2 0.5],[3 0.5],[4 0.5],[5 0.5],[6 0.5],[7 0.5],[8 0.5]});
%    makeSelectionPlots('table','ListOfParams',listOfParams,'RecomputeTheta',false,'RecomputeOrth',false,'saveOrth',false,...
%         'SavePostselection',true,'SaveTheta',false,'GetDelay',true,'RemoveModulation',true,'XUnit','ps','VaryAPS',true,'FitType','voigt');
%     listOfParams = struct('Type',{'fullcircle'},'Position',{[0.5 0.25],[1 0.25],...
%         [2 0.5],[3 0.5],[4 0.5],[5 0.5],[6 0.5],[7 0.5],[8 0.5]}); 
%      makeSelectionPlots('radiusPlots','ListOfParams',listOfParams,'RecomputeTheta',false,'RecomputeOrth',false,'saveOrth',false,...
%         'SavePostselection',false,'SaveTheta',false,'GetDelay',true,'RemoveModulation',true,'XUnit','ps','VaryAPS',true,'FitType','voigt');
    
%% Thickness Series
% listOfParamsT = struct('Type',{'fullcircle'},'Position',{[0 0.05],[0 0.1],[0,0.15],...
%         [0 0.2],[0 0.4],[0 0.6],[0 0.8],[0 1]});    
% makeSelectionPlots('radiusPlots','ListOfParams',listOfParamsT,'RecomputeTheta',false,...
%     'RecomputeOrth',false,'saveOrth',false,...
%     'SavePostselection',false,'SaveTheta',false,'GetDelay',true,'RemoveModulation',false,'XUnit','ps','VaryAPS',true);
end;
toc